---
title: "p8105_hw3_ww2745"
author: "ww2745"
date: "2024-10-14"
output: github_document
---

```{r setup}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

##Problem 2

Load and organize the dataset.
```{r load_tidy}
demo_df=
  read_csv(file="./data/nhanes_covar.csv",
           skip = 4) |> 
  janitor::clean_names() |> 
  filter(age>21) |> 
  drop_na() |> 
  mutate(
    sex = 
      case_match(
        sex, 
        1 ~ "male", 
        2 ~ "female"),
    sex = as.factor(sex))
    
demo_df

acc_df=
  read_csv(file="./data/nhanes_accel.csv") |> 
  janitor::clean_names() |> 
  pivot_longer(
    min1:min1440,
    names_to = "minute",
    names_prefix = "min",
    values_to = "mims"
  ) |> 
  mutate(
    minute = as.factor(minute))
acc_df

merge_df = 
  left_join(acc_df, demo_df, by = "seqn")
merge_df
```

Exploratory analyses based on education level.

This is a table for the number of men and women in each education category.
```{r num_edu}
merge_df |>
  mutate(
    education = 
      case_match(
        education, 
        1 ~ "less_than_high_school", 
        2 ~ "high_school_equivalent",
        3 ~ "more_than_high_school"),
    education = as.factor(education)) |> 
  group_by(sex, education) |>
  summarize(n_obs = n())
```
Most of the participants have education level at least equivalent to high school.

This graph shows the age distributions for men and women in each education category.
```{r }

```

